### PR TITLE
Fix unmount fail with commit

### PR DESCRIPTION
**Pull request by Zex**

### CODE REVIEW

**Comment by Zex** [comment]
False means no changes should be committed to the WIM, so discard is fine in this case

**Comment by yetanotherchris** [comment]
I mean what is the point of the `commitChanges?` line? It will always be `DismApi.DISM_DISCARD_IMAGE`

**Comment by Zex** [comment]
It exists in primary version of this file, isn't it? If commitChanges parameter is true, exception raises when unmount the wim image.

**Comment by yetanotherchris** [comment]
Sorry for the delay, I misread the diff

**Pull request merged**
